import type { Metadata } from "next";
import { AuthProvider } from "../context/auth";
import Navbar from "../components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "SNS Udemy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="ja">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
